console.log("1st session js")
//var
var a = 4;
var b = 5;
var c = "ishu"
console.log(a + b + 9)
console.log( typeof a , typeof b , typeof c)

//let 
let d = 4;
let e = 9;
let f = 3;
f = f + 8

{
    let f = 98
    console.log(f)
}
console.log(f)

//primitive data types 
let i = "ishukumar";
let j = 38;
let k = 34.8;
let l = true;
let m = null;
let n = undefined;
console.log(i , j, k, l, m, n,);
console.log(typeof i , typeof j,typeof  k, typeof l,typeof  m, typeof typeof n,)

//object

let o = {
    name:"ishu",
    "roll no": 1,
}
console.log(o)
o. subject = "english",  // add object
console.log(o)
o. subject = "hindi"
console.log(o)